name: shibui
favicon: null
layout_spectrum: 0.18156182020902634
typography_spectrum: 0.6011925763450563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4315841372590512
  lightness: 0.4214768430683762
  saturation: 0.5139679149724543
  rhythmicContrast: 0.7413371312431991
purpose: []
