name: shibui
favicon: null
layout_spectrum: 0.16135
typography_spectrum: 0.21949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#8f3b20'
    - '#b6612a'
    - '#e9b862'
    - '#fdfee9'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.7413371312431991
purpose: []
